### ISSUE TITLE
Extension incorrectly reports Nonexistent passage when using nested quotes

### ISSUE THREAD

**Issue by BawdyInkSlinger** [cyrusfirheir/twee3-language-tools#127]
![image](https://user-images.githubusercontent.com/51732963/230529945-00a3dd53-6824-424a-99df-c5e68e4948d8.png)
![image](https://user-images.githubusercontent.com/51732963/230529999-33f56de9-04a1-4212-aaba-95fb610fe86b.png)

For testing purposes, I made a strange passage name:

```
:: Test Pagination "'Nested Buttons'" [pagination:5 demo]
```

Elsewhere, I have a macro refer to this passage:

```
<<act "Passage with less pages than current" "Test Pagination \"'Nested Buttons'\"">><</act>>
```

I get a warning on the second parameter saying: `Nonexistent passage: "Test Pagination \"'Nested Buttons'\""sc2-ex(110)`

I expected no warnings.

This is how the macro is defined in my config:

```yml
    act:
      name: act
      container: true
      parameters:
        - text |+ (passage|undefined) |+ text
```
