### ISSUE TITLE
The quickfix link sometimes disappears on mouse hover

### ISSUE THREAD

**Issue by BawdyInkSlinger** [cyrusfirheir/twee3-language-tools#135]
This is my config file: 

```yml
sugarcube-2:
  macros:
    dialogelement:
      name: dialogelement
      container: true
    dialogelementclose:
      name: dialogelementclose
    opendialogelement:
      name: opendialogelement
      container: true
      parameters: 
      - "text"
```

This is my twee file:

```
<<dialogelement "Dialog 4" `"dialog-number-" + $dialog_number`>>
  <<button "Custom close button">><<dialogelementclose>><</button>>
<<onopen>>
  <<append "#event-log">><p>Opened 4</p><</append>>
<<onclose>>
  <<append "#event-log">><p>Closed 4</p><</append>>
<</dialogelement>>
```

This is what happens when I try to add those children to the config with a quick fix:

![gif](https://github.com/cyrusfirheir/twee3-language-tools/assets/51732963/d54e5b0e-01b6-49a1-bf1d-49abf6071e5a)
