### ISSUE TITLE
Add enums for sc2 macro definitions

### ISSUE THREAD

**Issue by JustNoon** [cyrusfirheir/twee3-language-tools#139]
Adding global enums to macro definitions would let code, documentation, and argument validation reuse values for more robust and convenient documentation.

```yaml
sugarcube-2:
  enums:
    colors: '"red"|"green"|"blue"|"pink"'
  macros:
    coloredbutton:
      name: coloredbutton
      description: |-
        `<<coloredbutton label color>>`
        
        `label`: What the button says
        
        `color`: %colors%
      parameters:
        - 'text &+ %colors%'
```

Global enums can be evaluated when requested or cached after all files evaluated.

Local would be useful too if global are too much. Thoughts?
