### ISSUE TITLE
SugarCube 2 parameters parsing error

### ISSUE THREAD

**Issue by ezsh** [cyrusfirheir/twee3-language-tools#42]
I want to add a definition for a macro that takes either a single or three parameters. This exact case is covered in the wiki page (`a |+ b&+ c`). However, given the following definition:

```yaml
NPC:
    name: NPC
    parameters:
        - string |+ string &+ string
```
and the code `<<NPC "Captain">>`, the extension complains "Expected type 'string' but there was no argumentsc2-ex(109)".

A workaround
```yaml
parameters:
          - string
          - string &+ string &+ string
```
works fine.
